### ISSUE TITLE
Excessive saturation ratio on Gelatin

### ISSUE THREAD

**Issue by Lykrast** [Bluberry-Kat/Gumobtainium#10]
Those screenshots with AppleSkin will speak for themselves:

![image](https://user-images.githubusercontent.com/8684850/62332736-0e1d4d80-b4c1-11e9-8abf-a68d0d02e70f.png)
![image](https://user-images.githubusercontent.com/8684850/62332738-137a9800-b4c1-11e9-8b74-893b8a08e67c.png)

For the values to be this big it doesn't really look intended.

**Comment by Bluberry-Kat** [comment]
yeah, this is unintentional. this was fixed in a pr awhile back (#2) but the mod has been stuck in dev for a while.

**Comment by Bluberry-Kat** [comment]
for clarity: gelatin *is* meant to be a bit of a superfood, but not to humorous extents. it's a bit of a pain to make, and you're supposed to be rewarded for having it automated. i'm not even sure if it beats out steak density-wise, if you were to compare 12 of those to 1 gelatin ingot.

**Comment by Bluberry-Kat** [comment]
released on fb2696f
